# Generated by Django 2.1.7 on 2019-09-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('received_qty', models.IntegerField()),
                ('rejected_qty', models.IntegerField()),
                ('unit_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_reason', models.CharField(max_length=1000)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvsivapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SRV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_receipt', models.CharField(choices=[('PO', 'PO'), ('LOA', 'LOA'), ('MRN', 'MRN'), ('STV', 'STV'), ('MTN', 'MTN')], max_length=10)),
                ('indent_department', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=1000)),
                ('name_supplier', models.CharField(max_length=50)),
                ('indent_ref_no', models.CharField(max_length=50)),
                ('indent_date', models.DateField()),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins', to='srvsivapi.Employee')),
                ('inspected_countersigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscounter', to='srvsivapi.Employee')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='srvsivapi.Employee')),
                ('received_countersigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivecounter', to='srvsivapi.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='siv',
            name='srv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvsivapi.SRV'),
        ),
        migrations.AddField(
            model_name='items',
            name='srv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvsivapi.SRV'),
        ),
    ]
