# Generated by Django 2.1.7 on 2019-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvsivapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(max_length=15),
        ),
    ]
